import { createHash } from 'crypto';
import { spawn } from 'child_process';
import { once } from 'events';
import {
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'fs';
import { tmpdir } from 'os';
import { dirname, join, resolve } from 'path';
import { setTimeout as delay } from 'timers/promises';
import { fileURLToPath } from 'url';
import { describe, expect, it } from 'vitest';

import {
  assertFreshIsolatedNativeBuildTarget,
  assertPinnedGeneratedJsonVectorDigest,
  assertNoNativeBuildDescendants,
  assertPinnedGeneratedJsonVectorMatch,
  BoundedProcessExitError,
  buildPinnedLocalNativeCargoArgs,
  buildPinnedLocalNativeReproducibleRustFlags,
  canonicalizePinnedGeneratedJsonVectorBytes,
  createPinnedLocalNativeBuildWorkspace,
  EXPECTED_CONSENSUS_SOURCE_LOCK_SHA256,
  EXPECTED_NATIVE_VERIFIER_TOOLCHAIN_LOCK_SHA256,
  runBoundedNativeBuildProcess,
  terminateNativeBuildProcessTree,
  validateNativeVerifierToolchainLock,
  type NativeVerifierBuildToolObservation,
} from './pinned-local-native-verifier-build.js';

const directory = dirname(fileURLToPath(import.meta.url));
const bridgeRoot = resolve(directory, '..', '..');
const PROCESS_LIFECYCLE_TEST_TIMEOUT_MS = process.platform === 'win32'
  ? 60_000
  : 30_000;
const LIVE_PROCESS_MARKER_TIMEOUT_MS = process.platform === 'win32'
  ? 40_000
  : 2_000;
const toolchainLockPath = resolve(
  bridgeRoot,
  'sources',
  'native-verifier-toolchain-lock.json',
);
const toolchainLock = JSON.parse(readFileSync(toolchainLockPath, 'utf8')) as Record<
  string,
  unknown
>;
const windowsObservation: NativeVerifierBuildToolObservation = {
  platformKey: 'win32-x64',
  rustTarget: 'x86_64-pc-windows-msvc',
  cargo: {
    version: 'cargo 1.82.0 (8f40fc59f 2024-08-21)',
    sha256: 'e0d72a8a6fc72c5bbaf88eb028fbdc0e0f9eb2aaaebb77d2b7271a9d09798aa2',
  },
  rustc: {
    version: 'rustc 1.82.0 (f6e511eec 2024-10-15)',
    sha256: '443b551e5248e5d8ebd0103dbb66e2e25d218ccd4195cdac3fbdc8f3f8dec455',
  },
  git: {
    version: 'git version 2.54.0.windows.1',
    sha256: '81ef35ae005ca9318018d18e3327578ce939fb99feaad6b2d7c8ab15f3de8db5',
  },
};

describe('pinned local native verifier build conformance', () => {
  it('builds only the eight runtime binaries and six pinned-vector generators', () => {
    const frontierSourcePath = resolve(bridgeRoot, '.source-cache', 'frontier-patched');
    const buildTargetPath = resolve(tmpdir(), 'e2s-pinned-local-native-example');
    const args = buildPinnedLocalNativeCargoArgs({
      frontierSourcePath,
      buildTargetPath,
      rustTarget: 'x86_64-pc-windows-msvc',
      offline: true,
    });

    expect(args).toEqual([
      'build',
      '--locked',
      '--offline',
      '--target-dir',
      buildTargetPath,
      '--target',
      'x86_64-pc-windows-msvc',
      '--manifest-path',
      resolve(frontierSourcePath, 'Cargo.toml'),
      '-p',
      'bridge-checkpoint-verifier',
      '--bin',
      'bridge-checkpoint-verifier',
      '--bin',
      'bridge-rpc-proof-codec',
      '--bin',
      'bridge-peg-in-frontier-event-v1-verifier',
      '--bin',
      'generate-peg-in-frontier-event-v1-fixture',
      '--bin',
      'bridge-peg-in-frontier-contract-state-v1-verifier',
      '--bin',
      'generate-peg-in-frontier-contract-state-v1-fixture',
      '--bin',
      'bridge-peg-in-frontier-mint-transition-v1-verifier',
      '--bin',
      'generate-peg-in-frontier-mint-transition-v1-fixture',
      '--bin',
      'bridge-peg-in-causal-mint-transition-v2-verifier',
      '--bin',
      'generate-peg-in-causal-mint-transition-v2-fixture',
      '--bin',
      'bridge-peg-in-causal-mint-transition-v3-verifier',
      '--bin',
      'generate-peg-in-causal-mint-transition-v3-fixture',
      '--bin',
      'bridge-peg-in-causal-source-proof-result-v1-producer',
      '--bin',
      'generate-peg-in-causal-source-proof-result-v1-fixture',
    ]);
    expect(args).not.toContain('--bins');
  });

  it('canonicalizes only checkout EOLs and one optional final newline', () => {
    const generated = '{\n  "schema": "vector.v1"\n}';
    const windowsCheckout = '{\r\n  "schema": "vector.v1"\r\n}\r\n';
    expect(canonicalizePinnedGeneratedJsonVectorBytes(generated))
      .toEqual(Buffer.from(generated, 'utf8'));
    expect(canonicalizePinnedGeneratedJsonVectorBytes(windowsCheckout))
      .toEqual(Buffer.from(generated, 'utf8'));
    expect(() => canonicalizePinnedGeneratedJsonVectorBytes(`${generated}\n\n`))
      .toThrow(/more than one trailing newline/i);
    expect(() => canonicalizePinnedGeneratedJsonVectorBytes(`\ufeff${generated}`))
      .toThrow(/BOM/i);
    expect(() => canonicalizePinnedGeneratedJsonVectorBytes('{\n'))
      .toThrow(/valid JSON/i);
  });

  it('rejects tracked-vector drift during generation before accepting generated bytes', () => {
    const initial = Buffer.from('{"schema":"vector.v1"}', 'utf8');
    const drifted = Buffer.from('{"schema":"vector.v2"}', 'utf8');
    expect(() => assertPinnedGeneratedJsonVectorMatch({
      initiallyTrackedCanonicalBytes: initial,
      currentlyTrackedCanonicalBytes: drifted,
      generatedCanonicalBytes: initial,
    })).toThrow(/changed during generation/i);
    expect(() => assertPinnedGeneratedJsonVectorMatch({
      initiallyTrackedCanonicalBytes: initial,
      currentlyTrackedCanonicalBytes: initial,
      generatedCanonicalBytes: drifted,
    })).toThrow(/differs from the tracked vector/i);
    expect(assertPinnedGeneratedJsonVectorMatch({
      initiallyTrackedCanonicalBytes: initial,
      currentlyTrackedCanonicalBytes: initial,
      generatedCanonicalBytes: initial,
    })).toBe(`0x${createHash('sha256').update(initial).digest('hex')}`);
  });

  it('rehashes the current tracked vector before reusing its build identity', () => {
    const tracked = '{\r\n  "schema": "vector.v1"\r\n}\r\n';
    const canonical = Buffer.from('{\n  "schema": "vector.v1"\n}', 'utf8');
    const expectedSha256Hex =
      `0x${createHash('sha256').update(canonical).digest('hex')}`;

    expect(assertPinnedGeneratedJsonVectorDigest({
      value: tracked,
      expectedSha256Hex,
      label: 'causal V3',
    })).toBe(expectedSha256Hex);
    expect(() => assertPinnedGeneratedJsonVectorDigest({
      value: '{"schema":"vector.v2"}',
      expectedSha256Hex,
      label: 'causal V3',
    })).toThrow(/changed after pinned local build/i);
  });

  it('pins local reproducibility flags and requests deterministic MSVC linking', () => {
    const flags = buildPinnedLocalNativeReproducibleRustFlags({
      frontierSourcePath: resolve(bridgeRoot, '.source-cache', 'frontier-patched'),
      buildTargetPath: resolve(tmpdir(), 'e2s-pinned-local-native-example'),
      rustTarget: 'x86_64-pc-windows-msvc',
    });

    expect(flags).toEqual([
      expect.stringMatching(/^--remap-path-prefix=.*=\/e2s\/frontier-source$/),
      expect.stringMatching(/^--remap-path-prefix=.*=\/e2s\/build-target$/),
      '-Cdebuginfo=0',
      '-Ccodegen-units=1',
      '-Clink-arg=/Brepro',
    ]);
    expect(Object.isFrozen(flags)).toBe(true);

    const nonMsvcFlags = buildPinnedLocalNativeReproducibleRustFlags({
      frontierSourcePath: resolve(bridgeRoot, '.source-cache', 'frontier-patched'),
      buildTargetPath: resolve(tmpdir(), 'e2s-pinned-local-native-example'),
      rustTarget: 'x86_64-unknown-linux-gnu',
    });
    expect(nonMsvcFlags).not.toContain('-Clink-arg=/Brepro');
  });

  it('creates the Windows target suspended inside a kill-on-close Job Object', () => {
    const source = readFileSync(
      resolve(directory, 'scripts', 'windows-job-process.ps1'),
      'utf8',
    );
    expect(source).toContain('JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE');
    expect(source).toContain('CREATE_SUSPENDED');
    expect(source).toContain('TerminateJobObject cancellation');
    expect(source).toContain('TerminateJobObject completion');
    expect(source).toContain('QueryInformationJobObject');
    expect(source).toContain('accounting.ActiveProcesses == 0');
    expect(source).toContain('TARGET_FAILURE_EXIT_CODE');
    expect(source).toContain('WRAPPER_FAILURE_CONTAINED_EXIT_CODE');
    expect(source).toContain('TARGET_TIMEOUT_EXIT_CODE');
    expect(source).toContain('targetTimeoutMilliseconds - targetRuntime.ElapsedMilliseconds');
    expect(source).toContain('TryVerifyExceptionalContainment');
    expect(source).toContain('assignedToJob');
    expect(source).toContain('Console.OpenStandardInput().ReadByte()');
    expect(source).not.toMatch(/JOB_OBJECT_LIMIT_(?:SILENT_)?BREAKAWAY_OK/);
    expect(source.indexOf('AssignProcessToJobObject(job, processInformation.hProcess)'))
      .toBeLessThan(source.indexOf('ResumeThread(processInformation.hThread)'));
    expect(source.indexOf('Stopwatch targetRuntime = Stopwatch.StartNew()'))
      .toBeLessThan(source.indexOf('ResumeThread(processInformation.hThread)'));
  });

  it('retains the exact historical native source lock while the current lock advances', () => {
    const currentSourceLockPath = resolve(
      bridgeRoot,
      'sources',
      'consensus-source-lock.json',
    );
    const historicalSourceLockPath = resolve(
      bridgeRoot,
      'sources',
      'authenticated-v2-compiler-consensus-source-lock-v1.json',
    );
    const currentSourceLock = JSON.parse(readFileSync(currentSourceLockPath, 'utf8')) as {
      ergoNode: {
        baseCommit: string;
        patchSha256: string;
        files: Array<{ patchedBlob: string }>;
      };
    };
    const historicalSourceLock = JSON.parse(
      readFileSync(historicalSourceLockPath, 'utf8'),
    ) as typeof currentSourceLock;
    const compilerLock = JSON.parse(readFileSync(resolve(
      bridgeRoot,
      'sources',
      'authenticated-v2-compiler-lock.json',
    ), 'utf8')) as {
      consensusSourceLockSha256: string;
      ergoNodeBaseCommit: string;
      ergoPatchSha256: string;
      ergoPatchedBlobIds: string[];
    };

    expect(sha256(currentSourceLockPath)).not.toBe(EXPECTED_CONSENSUS_SOURCE_LOCK_SHA256);
    expect(sha256(historicalSourceLockPath)).toBe(EXPECTED_CONSENSUS_SOURCE_LOCK_SHA256);
    expect(compilerLock.consensusSourceLockSha256)
      .toBe(EXPECTED_CONSENSUS_SOURCE_LOCK_SHA256);
    expect(currentSourceLock.ergoNode).toEqual(historicalSourceLock.ergoNode);
    expect(historicalSourceLock.ergoNode.baseCommit).toBe(compilerLock.ergoNodeBaseCommit);
    expect(historicalSourceLock.ergoNode.patchSha256).toBe(compilerLock.ergoPatchSha256);
    expect(historicalSourceLock.ergoNode.files.map(file => file.patchedBlob).sort())
      .toEqual([...compilerLock.ergoPatchedBlobIds].sort());
    expect(sha256(toolchainLockPath)).toBe(EXPECTED_NATIVE_VERIFIER_TOOLCHAIN_LOCK_SHA256);
  });

  it('accepts only the exact pinned platform tool identities', () => {
    expect(validateNativeVerifierToolchainLock(toolchainLock, windowsObservation).errors)
      .toEqual([]);

    const wrongCargo = structuredClone(windowsObservation);
    wrongCargo.cargo.sha256 = 'ff'.repeat(32);
    expect(validateNativeVerifierToolchainLock(toolchainLock, wrongCargo).errors)
      .toContain('Cargo executable digest mismatch');

    const unsupported = structuredClone(windowsObservation);
    unsupported.platformKey = 'linux-x64';
    expect(validateNativeVerifierToolchainLock(toolchainLock, unsupported).errors)
      .toContain('toolchain lock has no pinned profile for linux-x64');
  });

  it('rejects a weakened toolchain boundary', () => {
    const weakened = structuredClone(toolchainLock) as {
      boundaries: { isolatedCargoTargetRequired: boolean };
    };
    weakened.boundaries.isolatedCargoTargetRequired = false;
    expect(validateNativeVerifierToolchainLock(weakened, windowsObservation).errors)
      .toContain('toolchain lock must require isolated Cargo target');
  });

  it('keeps local conformance separate from build and admission attestation', () => {
    const boundaries = toolchainLock.boundaries as Record<string, unknown>;

    expect(boundaries).toMatchObject({
      completeBuildToolClosureVerifiedByThisLock: false,
      dependencyCacheContentAttestedByThisLock: false,
      independentBuildAttestationVerifiedByThisLock: false,
      localConformanceOnly: true,
      admissionEligible: false,
    });
    expect(validateNativeVerifierToolchainLock(toolchainLock, windowsObservation).errors)
      .toEqual([]);

    const overstated = structuredClone(toolchainLock) as {
      boundaries: { independentBuildAttestationVerifiedByThisLock: boolean };
    };
    overstated.boundaries.independentBuildAttestationVerifiedByThisLock = true;
    expect(validateNativeVerifierToolchainLock(overstated, windowsObservation).errors)
      .toContain('toolchain lock must not claim independent build attestation');
  });

  it('rejects any pre-existing content in the isolated Cargo target', () => {
    const target = mkdtempSync(join(tmpdir(), 'e2s-pinned-local-native-'));
    try {
      expect(() => assertFreshIsolatedNativeBuildTarget(target)).not.toThrow();
      writeFileSync(resolve(target, 'bridge-checkpoint-verifier.exe'), 'stale');
      expect(() => assertFreshIsolatedNativeBuildTarget(target))
        .toThrow(/must be empty before Cargo starts/i);
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('removes the isolated target when Cargo-home preparation fails', () => {
    const cargoHome = mkdtempSync(join(tmpdir(), 'e2s-invalid-cargo-home-'));
    const invalidRegistryPath = resolve(cargoHome, 'registry');
    const previousCargoHome = process.env.CARGO_HOME;
    writeFileSync(invalidRegistryPath, 'not a directory');
    process.env.CARGO_HOME = cargoHome;

    let allocatedTargetPath: string | undefined;
    try {
      expect(() => createPinnedLocalNativeBuildWorkspace(path => {
        allocatedTargetPath = path;
      })).toThrow(/shared Cargo cache must be a regular directory/i);
      expect(allocatedTargetPath).toBeDefined();
      expect(existsSync(allocatedTargetPath!)).toBe(false);
    } finally {
      if (previousCargoHome === undefined) delete process.env.CARGO_HOME;
      else process.env.CARGO_HOME = previousCargoHome;
      rmSync(cargoHome, { recursive: true, force: true });
    }
  });

  it('copies the Cargo dependency cache for offline builds without host-cache mutation', () => {
    const sharedCargoHome = mkdtempSync(join(tmpdir(), 'e2s-shared-cargo-home-'));
    const sourceRegistry = resolve(sharedCargoHome, 'registry');
    mkdirSync(sourceRegistry);
    const sourceEntry = resolve(sourceRegistry, 'entry.txt');
    writeFileSync(sourceEntry, 'host-cache', 'utf8');
    const previousCargoHome = process.env.CARGO_HOME;
    process.env.CARGO_HOME = sharedCargoHome;
    let workspace: ReturnType<typeof createPinnedLocalNativeBuildWorkspace> | undefined;
    try {
      workspace = createPinnedLocalNativeBuildWorkspace(undefined, {
        cargoDependencyMode: 'private-copy-offline',
      });
      const copiedRegistry = resolve(workspace.cargoHomePath, 'registry');
      const copiedEntry = resolve(copiedRegistry, 'entry.txt');
      expect(lstatSync(copiedRegistry).isSymbolicLink()).toBe(false);
      expect(readFileSync(copiedEntry, 'utf8')).toBe('host-cache');
      writeFileSync(copiedEntry, 'worker-private-copy', 'utf8');
      expect(readFileSync(sourceEntry, 'utf8')).toBe('host-cache');
    } finally {
      workspace?.cleanup();
      if (previousCargoHome === undefined) delete process.env.CARGO_HOME;
      else process.env.CARGO_HOME = previousCargoHome;
      rmSync(sharedCargoHome, { recursive: true, force: true });
    }
  });

  it('allocates and cleans a build workspace under an explicit temporary root', () => {
    const temporaryRoot = mkdtempSync(join(tmpdir(), 'e2s-build-root-'));
    const sharedCargoHome = resolve(temporaryRoot, 'shared-cargo-home');
    const sharedRegistry = resolve(sharedCargoHome, 'registry');
    mkdirSync(sharedCargoHome);
    mkdirSync(sharedRegistry);
    writeFileSync(resolve(sharedRegistry, 'entry.txt'), 'shared-cache', 'utf8');
    let workspace: ReturnType<typeof createPinnedLocalNativeBuildWorkspace> | undefined;
    let allocatedTargetPath: string | undefined;
    try {
      workspace = createPinnedLocalNativeBuildWorkspace(targetPath => {
        allocatedTargetPath = targetPath;
        assertFreshIsolatedNativeBuildTarget(targetPath, temporaryRoot);
      }, {
        sharedCargoHomeRoot: sharedCargoHome,
        temporaryDirectoryRoot: temporaryRoot,
      });
      expect(workspace.buildTargetPath).toBe(allocatedTargetPath);
      expect(dirname(workspace.buildTargetPath)).toBe(temporaryRoot);
      expect(existsSync(workspace.cargoHomePath)).toBe(true);
      expect(readFileSync(
        resolve(workspace.cargoHomePath, 'registry', 'entry.txt'),
        'utf8',
      )).toBe('shared-cache');
      const allocatedPath = workspace.buildTargetPath;
      workspace.cleanup();
      workspace = undefined;
      expect(existsSync(allocatedPath)).toBe(false);
    } finally {
      workspace?.cleanup();
      rmSync(temporaryRoot, { recursive: true, force: true });
    }
  });

  it('rejects process timeouts that exceed the Node timer range', async () => {
    await expect(runBoundedNativeBuildProcess({
      executablePath: process.execPath,
      args: ['--version'],
      cwd: bridgeRoot,
      env: process.env,
      timeoutMs: Number.MAX_SAFE_INTEGER,
      maxOutputBytes: 1024,
      label: 'test native build',
    })).rejects.toThrow(/timeout exceeds the supported timer range/i);
  });

  it('retains bounded process output on a non-zero exit', async () => {
    const outcome = await captureProcessOutcome(runBoundedNativeBuildProcess({
      executablePath: process.execPath,
      args: [
        '-e',
        "process.stdout.write('producer-out'); process.stderr.write('producer-err'); process.exit(23);",
      ],
      cwd: bridgeRoot,
      env: minimalTestProcessEnvironment(),
      timeoutMs: 5_000,
      maxOutputBytes: 1_024,
      label: 'test bounded diagnostics',
    }));

    expect(outcome.status).toBe('rejected');
    if (outcome.status !== 'rejected') return;
    expect(outcome.error).toBeInstanceOf(BoundedProcessExitError);
    expect(outcome.error).toMatchObject({
      stdout: 'producer-out',
      stderr: 'producer-err',
      message: 'test bounded diagnostics failed',
    });
    expect((outcome.error as BoundedProcessExitError).exitCode).not.toBe(0);
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('waits for a timed-out process tree to stop before returning cleanup authority', async () => {
    const workspace = createPinnedLocalNativeBuildWorkspace();
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-timeout-marker-'));
    const readyPath = resolve(markerRoot, 'descendant-ready.txt');
    const descendantScript = [
      "const { writeFileSync } = require('fs');",
      "writeFileSync(process.env.READY_PATH, String(process.pid));",
      'setInterval(() => {}, 1000);',
    ].join(' ');
    const parentScript = [
      "const { spawn } = require('child_process');",
      `spawn(process.execPath, ['-e', ${JSON.stringify(descendantScript)}], ` +
        "{ stdio: 'ignore', windowsHide: true, env: process.env });",
      'setInterval(() => {}, 1000);',
    ].join(' ');
    let execution: ReturnType<typeof captureProcessOutcome> | undefined;

    try {
      execution = captureProcessOutcome(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', parentScript],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment({
          READY_PATH: readyPath,
        }),
        timeoutMs: 5_000,
        maxOutputBytes: 1_024,
        terminationGraceMs: 1,
        label: 'test native build',
      }));
      const descendantPid = await waitForLiveProcessMarker(
        readyPath,
        LIVE_PROCESS_MARKER_TIMEOUT_MS,
      );

      const outcome = await execution;
      expect(outcome.status).toBe('rejected');
      if (outcome.status === 'rejected') expect(outcome.error).toMatchObject({
        message: expect.stringMatching(/timed out/i),
      });
      expect(isProcessRunning(descendantPid)).toBe(false);

      workspace.cleanup();
      expect(existsSync(workspace.buildTargetPath)).toBe(false);
    } finally {
      if (execution) await execution;
      workspace.cleanup();
      rmSync(markerRoot, { recursive: true, force: true });
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('waits for an output-overflow process to stop before cleanup', async () => {
    const workspace = createPinnedLocalNativeBuildWorkspace();
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-overflow-marker-'));
    const readyPath = resolve(markerRoot, 'descendant-ready.txt');
    const triggerPath = resolve(markerRoot, 'emit-output.txt');
    const descendantScript = [
      "const { writeFileSync } = require('fs');",
      "writeFileSync(process.env.READY_PATH, String(process.pid));",
      'setInterval(() => {}, 1000);',
    ].join(' ');
    const parentScript = [
      "const { existsSync } = require('fs');",
      "const { spawn } = require('child_process');",
      `spawn(process.execPath, ['-e', ${JSON.stringify(descendantScript)}], ` +
        "{ stdio: 'ignore', windowsHide: true, env: process.env });",
      'const poll = setInterval(() => {',
      'if (!existsSync(process.env.TRIGGER_PATH)) return;',
      'clearInterval(poll);',
      "process.stdout.write('x'.repeat(4096));",
      'setInterval(() => {}, 1000);',
      '}, 10);',
    ].join(' ');
    let execution: ReturnType<typeof captureProcessOutcome> | undefined;

    try {
      execution = captureProcessOutcome(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', parentScript],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment({
          READY_PATH: readyPath,
          TRIGGER_PATH: triggerPath,
        }),
        timeoutMs: 5_000,
        maxOutputBytes: 8_192,
        maxStdoutBytes: 1_024,
        maxStderrBytes: 8_192,
        label: 'test native build',
      }));
      const descendantPid = await waitForLiveProcessMarker(
        readyPath,
        LIVE_PROCESS_MARKER_TIMEOUT_MS,
      );
      writeFileSync(triggerPath, 'emit bounded overflow');

      const outcome = await execution;
      expect(outcome.status).toBe('rejected');
      if (outcome.status === 'rejected') expect(outcome.error).toMatchObject({
        message: expect.stringMatching(/stdout exceeded the limit/i),
      });
      expect(isProcessRunning(descendantPid)).toBe(false);

      workspace.cleanup();
      expect(existsSync(workspace.buildTargetPath)).toBe(false);
    } finally {
      if (execution) await execution;
      workspace.cleanup();
      rmSync(markerRoot, { recursive: true, force: true });
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('rejects output overflow that races verified Windows process completion', async () => {
    if (process.platform !== 'win32') return;
    const workspace = createPinnedLocalNativeBuildWorkspace();
    try {
      const outcome = await captureProcessOutcome(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: [
          '-e',
          "process.stdout.write('x'.repeat(4096), () => process.exit(0));",
        ],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment(),
        timeoutMs: 5_000,
        maxOutputBytes: 8_192,
        maxStdoutBytes: 1_024,
        maxStderrBytes: 8_192,
        label: 'test native build completion race',
      }));
      expect(outcome.status).toBe('rejected');
      if (outcome.status === 'rejected') expect(outcome.error).toMatchObject({
        message: expect.stringMatching(/stdout exceeded the limit/i),
      });
    } finally {
      workspace.cleanup();
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('rejects a contained Windows wrapper failure without quarantining cleanup', async () => {
    if (process.platform !== 'win32') return;
    const workspace = createPinnedLocalNativeBuildWorkspace();
    try {
      const outcome = await captureProcessOutcome(runBoundedNativeBuildProcess({
        executablePath: resolve(workspace.buildTargetPath, 'missing-native-target.exe'),
        args: [],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment(),
        timeoutMs: 5_000,
        maxOutputBytes: 1_024,
        label: 'test contained wrapper failure',
      }));
      expect(outcome.status).toBe('rejected');
      if (outcome.status === 'rejected') expect(outcome.error).toMatchObject({
        message: expect.stringMatching(/failed/i),
      });
      workspace.cleanup();
      expect(existsSync(workspace.buildTargetPath)).toBe(false);
    } finally {
      workspace.cleanup();
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('terminates a process that exceeds its independent stderr limit', async () => {
    const workspace = createPinnedLocalNativeBuildWorkspace();
    try {
      const outcome = await captureProcessOutcome(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', "process.stderr.write('x'.repeat(4096)); setInterval(() => {}, 1000);"],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment(),
        timeoutMs: 5_000,
        maxOutputBytes: 8_192,
        maxStdoutBytes: 8_192,
        maxStderrBytes: 1_024,
        label: 'test native build stderr',
      }));
      expect(outcome.status).toBe('rejected');
      if (outcome.status === 'rejected') expect(outcome.error).toMatchObject({
        message: expect.stringMatching(/stderr exceeded the limit/i),
      });
    } finally {
      workspace.cleanup();
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('refuses PID-only process-tree termination after its parent exits', async () => {
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-overflow-marker-'));
    const readyPath = resolve(markerRoot, 'descendant-ready.txt');
    const descendantScript = 'setTimeout(() => process.exit(0), 700);';
    const parentScript = [
      "const { writeFileSync } = require('fs');",
      "const { spawn } = require('child_process');",
      `const child = spawn(process.execPath, ['-e', ${JSON.stringify(descendantScript)}], ` +
        "{ detached: true, stdio: 'ignore', windowsHide: true, env: process.env });",
      'child.unref();',
      "writeFileSync(process.env.READY_PATH, String(child.pid));",
      'process.exit(0);',
    ].join(' ');

    try {
      const parent = spawn(process.execPath, ['-e', parentScript], {
        windowsHide: true,
        shell: false,
        stdio: 'ignore',
        env: minimalTestProcessEnvironment({
          READY_PATH: readyPath,
        }),
      });
      await once(parent, 'close');
      expect(existsSync(readyPath)).toBe(true);
      expect(() => terminateNativeBuildProcessTree(parent))
        .toThrow(/parent has already exited/i);
      await delay(800);
    } finally {
      rmSync(markerRoot, { recursive: true, force: true });
    }
  });

  it('kills a detached descendant before a successful Windows run returns', async () => {
    if (process.platform !== 'win32') return;
    const workspace = createPinnedLocalNativeBuildWorkspace();
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-success-marker-'));
    const readyPath = resolve(markerRoot, 'descendant-ready.txt');
    const descendantScript = 'setTimeout(() => process.exit(0), 10000);';
    const parentScript = [
      "const { writeFileSync } = require('fs');",
      "const { spawn } = require('child_process');",
      `const child = spawn(process.execPath, ['-e', ${JSON.stringify(descendantScript)}], ` +
        "{ detached: true, stdio: 'ignore', windowsHide: true, env: process.env });",
      'child.unref();',
      "writeFileSync(process.env.READY_PATH, String(child.pid));",
      'process.exit(0);',
    ].join(' ');

    try {
      await expect(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', parentScript],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment({ READY_PATH: readyPath }),
        timeoutMs: 5_000,
        maxOutputBytes: 1024,
        label: 'test native build',
      })).resolves.toBeUndefined();
      const descendantPid = Number(readFileSync(readyPath, 'utf8'));
      expect(isProcessRunning(descendantPid)).toBe(false);
    } finally {
      workspace.cleanup();
      rmSync(markerRoot, { recursive: true, force: true });
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('closes inherited pipes by killing the contained Windows descendants', async () => {
    if (process.platform !== 'win32') return;
    const workspace = createPinnedLocalNativeBuildWorkspace();
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-inherited-pipe-marker-'));
    const readyPath = resolve(markerRoot, 'descendant-ready.txt');
    const descendantScript = 'setInterval(() => {}, 1000);';
    const parentScript = [
      "const { writeFileSync } = require('fs');",
      "const { spawn } = require('child_process');",
      `const child = spawn(process.execPath, ['-e', ${JSON.stringify(descendantScript)}], ` +
        "{ detached: true, stdio: ['ignore', 'inherit', 'inherit'], windowsHide: true, env: process.env });",
      'child.unref();',
      "writeFileSync(process.env.READY_PATH, String(child.pid));",
      'setTimeout(() => process.exit(0), 250);',
    ].join(' ');

    try {
      const execution = runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', parentScript],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment({ READY_PATH: readyPath }),
        timeoutMs: 15_000,
        maxOutputBytes: 1024,
        label: 'test native build',
      });
      await waitForLiveProcessMarker(readyPath, LIVE_PROCESS_MARKER_TIMEOUT_MS);
      const targetReadyAt = Date.now();
      await expect(execution).resolves.toBeUndefined();
      expect(Date.now() - targetReadyAt).toBeLessThan(12_000);
      expect(existsSync(workspace.buildTargetPath)).toBe(true);
      const descendantPid = Number(readFileSync(readyPath, 'utf8'));
      expect(isProcessRunning(descendantPid)).toBe(false);
    } finally {
      workspace.cleanup();
      rmSync(markerRoot, { recursive: true, force: true });
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('contains an orphaned grandchild after its intermediary exits', async () => {
    if (process.platform !== 'win32') return;
    const workspace = createPinnedLocalNativeBuildWorkspace();
    const markerRoot = mkdtempSync(join(tmpdir(), 'e2s-build-orphan-marker-'));
    const readyPath = resolve(markerRoot, 'grandchild-ready.txt');
    const grandchildScript = 'setInterval(() => {}, 1000);';
    const intermediaryScript = [
      "const { writeFileSync } = require('fs');",
      "const { spawn } = require('child_process');",
      `const grandchild = spawn(process.execPath, ['-e', ${JSON.stringify(grandchildScript)}], ` +
        "{ detached: true, stdio: 'ignore', windowsHide: true, env: process.env });",
      'grandchild.unref();',
      "writeFileSync(process.env.READY_PATH, String(grandchild.pid));",
      'process.exit(0);',
    ].join(' ');
    const parentScript = [
      "const { spawn } = require('child_process');",
      `const intermediary = spawn(process.execPath, ['-e', ${JSON.stringify(intermediaryScript)}], ` +
        "{ stdio: 'inherit', windowsHide: true, env: process.env });",
      "intermediary.once('close', () => process.exit(0));",
    ].join(' ');

    try {
      await expect(runBoundedNativeBuildProcess({
        executablePath: process.execPath,
        args: ['-e', parentScript],
        cwd: workspace.buildTargetPath,
        env: minimalTestProcessEnvironment({ READY_PATH: readyPath }),
        timeoutMs: 10_000,
        maxOutputBytes: 1024,
        label: 'test native build',
      })).resolves.toBeUndefined();
      const grandchildPid = Number(readFileSync(readyPath, 'utf8'));
      expect(isProcessRunning(grandchildPid)).toBe(false);
    } finally {
      workspace.cleanup();
      rmSync(markerRoot, { recursive: true, force: true });
    }
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);

  it('fails closed when an exited parent cannot be resolved through the process table', async () => {
    if (process.platform !== 'win32') return;
    const parent = spawn(process.execPath, ['-e', 'process.exit(0);'], {
      windowsHide: true,
      shell: false,
      stdio: 'ignore',
      env: minimalTestProcessEnvironment(),
    });
    await once(parent, 'close');

    expect(() => assertNoNativeBuildDescendants(parent, {
      collectWindowsDescendants: () => {
        throw new Error('forced process-table failure');
      },
    })).toThrow(/cannot inspect native build descendants/i);
  });

  it('accepts a terminated tree after transient descendant records disappear', async () => {
    if (process.platform !== 'win32') return;
    const parent = spawn(process.execPath, ['-e', 'process.exit(0);'], {
      windowsHide: true,
      shell: false,
      stdio: 'ignore',
      env: minimalTestProcessEnvironment(),
    });
    await once(parent, 'close');
    const snapshots = [[123], [123], []];

    expect(() => assertNoNativeBuildDescendants(parent, {
      collectWindowsDescendants: () => snapshots.shift() ?? [],
    })).not.toThrow();
  });

  it('fails closed when descendants persist through the inspection window', async () => {
    if (process.platform !== 'win32') return;
    const parent = spawn(process.execPath, ['-e', 'process.exit(0);'], {
      windowsHide: true,
      shell: false,
      stdio: 'ignore',
      env: minimalTestProcessEnvironment(),
    });
    await once(parent, 'close');

    expect(() => assertNoNativeBuildDescendants(parent, {
      collectWindowsDescendants: () => [123],
    })).toThrow(/descendants remain/i);
  }, PROCESS_LIFECYCLE_TEST_TIMEOUT_MS);
});

function sha256(path: string): string {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function minimalTestProcessEnvironment(
  extra: NodeJS.ProcessEnv = {},
): NodeJS.ProcessEnv {
  return {
    SystemRoot: process.env.SystemRoot,
    WINDIR: process.env.WINDIR,
    ...extra,
  };
}

function isProcessRunning(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ESRCH') return false;
    throw error;
  }
}

async function waitForLiveProcessMarker(path: string, timeoutMs: number): Promise<number> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (existsSync(path)) {
      const pid = Number(readFileSync(path, 'utf8'));
      if (Number.isSafeInteger(pid) && pid > 0 && isProcessRunning(pid)) return pid;
    }
    await delay(20);
  }
  throw new Error('timed out waiting for live test process marker');
}

function captureProcessOutcome(promise: Promise<void>): Promise<
  | { status: 'resolved' }
  | { status: 'rejected'; error: Error }
> {
  return promise.then(
    () => ({ status: 'resolved' as const }),
    error => ({
      status: 'rejected' as const,
      error: error instanceof Error ? error : new Error(String(error)),
    }),
  );
}
