import {
  EIP0045_BRIDGE_APPLICATION_PREACTIVATION_PROFILE_ID_HEX,
} from './spv-tracker-validity-v2.js';

export const POOLED_RESERVE_BURN_TRACKER_V5_PROGRAM_ID_HEX =
  'bd72f52090ed45f2803767f64cde4d4314b7735f27e8d4596c4db37f1dc52a31' as const;
export const POOLED_RESERVE_BURN_TRACKER_V5_VERIFIER_PROFILE_ID_HEX =
  EIP0045_BRIDGE_APPLICATION_PREACTIVATION_PROFILE_ID_HEX;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V5_DOMAIN =
  'E2S_POOLED_RESERVE_BURN_APPLICATION_BINDING_V5' as const;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V5_VERSION = 5 as const;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V5_BYTES = 486 as const;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V5_PREFIX_BYTES = 450 as const;
