import {
  EIP0045_BRIDGE_APPLICATION_PREACTIVATION_PROFILE_ID_HEX,
} from './spv-tracker-validity-v2.js';

export const POOLED_RESERVE_BURN_TRACKER_V4_PROGRAM_ID_HEX =
  'ad8ad97a4a060059e70e793fc10a311d1e16fbe05b7cdcbeb58aa597a60b3fe4' as const;
export const POOLED_RESERVE_BURN_TRACKER_V4_VERIFIER_PROFILE_ID_HEX =
  EIP0045_BRIDGE_APPLICATION_PREACTIVATION_PROFILE_ID_HEX;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V4_DOMAIN =
  'E2S_POOLED_RESERVE_BURN_APPLICATION_BINDING_V4' as const;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V4_BYTES = 485 as const;
export const POOLED_RESERVE_BURN_APPLICATION_BINDING_V4_PREFIX_BYTES = 449 as const;
