//! Host-side execution and verification for the preactivation bridge validity guest.
//!
//! A verified receipt is engineering evidence only. This crate does not activate an EIP-0045
//! profile, authorize settlement, or close Gate 5.

mod application_v2;
mod pooled_reserve_burn_v4;
mod pooled_reserve_burn_v5;

pub use application_v2::*;
pub use pooled_reserve_burn_v4::*;
pub use pooled_reserve_burn_v5::*;

#[cfg(feature = "local-prove")]
use bridge_validity_composition::MAX_BRIDGE_VALIDITY_GUEST_WITNESS_V1_BYTES;
use bridge_validity_statement::{
    decode_eip0045_bridge_statement_v1, StatementError, EIP0045_BRIDGE_STATEMENT_V1_BYTES,
};
#[cfg(feature = "local-prove")]
use bridge_validity_zkvm_methods::BRIDGE_VALIDITY_GUEST_ELF;
use bridge_validity_zkvm_methods::BRIDGE_VALIDITY_GUEST_ID;
use risc0_zkp::verify::VerificationError;
use risc0_zkvm::{Digest, InnerReceipt, Receipt};
#[cfg(feature = "local-prove")]
use risc0_zkvm::{
    ExecutorEnv, LocalProver, ProveInfo, Prover, ProverOpts, SessionStats, VerifierContext,
};
use thiserror::Error;

/// Exact preactivation RISC Zero v3 succinct profile ID frozen by EIP-0045 at
/// public draft commit `f32d4980053d110e6f2b7edf3b93288e75159706`.
pub const EIP0045_RISC0_V3_SUCCINCT_PROFILE_ID: [u8; 32] = [
    0x23, 0xc4, 0xa1, 0x23, 0xff, 0xb3, 0x3a, 0x1c, 0x8d, 0xb8, 0x94, 0x36, 0xfe, 0x0e, 0x79, 0x72,
    0xbd, 0x8e, 0x4e, 0x28, 0x94, 0x59, 0xee, 0x5f, 0xd7, 0x1b, 0xe5, 0x44, 0x06, 0x07, 0xd3, 0x83,
];
/// Blake2b-256 identity of the exact version-4, constant-segregated bridge
/// consumer proposition generated by SigmaState draft
/// `f78deadd668f801e7fae3bc884283f79c6f484fa`.
///
/// This is a preactivation conformance identity only. It does not activate the
/// opcode, authenticate a source chain, or authorize settlement.
pub const EIP0045_BRIDGE_VALIDITY_CONSUMER_CONTRACT_ID: [u8; 32] = [
    0x9d, 0x0a, 0xc3, 0xc2, 0xc7, 0x88, 0x9e, 0xf4, 0xbf, 0xa5, 0x3c, 0x31, 0x90, 0x3f, 0x5e, 0x11,
    0x01, 0x2f, 0x20, 0xb2, 0x41, 0x56, 0xcb, 0xcf, 0x82, 0xb3, 0x43, 0x5d, 0x95, 0xa2, 0x90, 0xfc,
];
/// Canonical raw succinct-seal partition required by the frozen profile.
pub const EIP0045_RISC0_V3_PROOF_CHUNK_BYTES: [usize; 4] = [65_535, 65_535, 65_535, 26_063];
/// Exact raw succinct-seal length required by the frozen profile.
pub const EIP0045_RISC0_V3_RAW_SEAL_BYTES: usize = 222_668;
/// Exact terminal `join` control ID expected for this multi-segment guest.
pub const EIP0045_RISC0_V3_JOIN_CONTROL_ID: [u8; 32] = [
    0x7a, 0x8f, 0x24, 0x09, 0x2c, 0x34, 0xed, 0x3e, 0xb8, 0x1b, 0x3d, 0x0a, 0x0b, 0x79, 0x6c, 0x58,
    0x8c, 0x61, 0x5d, 0x34, 0x88, 0xef, 0x9e, 0x61, 0xc2, 0x1d, 0xbd, 0x1e, 0x4b, 0x83, 0xea, 0x6e,
];

const EIP0045_RISC0_V3_OUTER_PO2: u32 = 18;

/// Host-side proof construction or receipt-binding rejection.
#[derive(Debug, Error)]
pub enum HostError {
    /// The caller supplied a private witness outside the guest ABI bound.
    #[cfg(feature = "local-prove")]
    #[error("private witness exceeds {max} bytes: {actual}")]
    WitnessTooLarge {
        /// Received bytes.
        actual: usize,
        /// Maximum bytes.
        max: usize,
    },
    /// The witness length cannot be represented by the framed guest input.
    #[cfg(feature = "local-prove")]
    #[error("private witness length exceeds u32")]
    WitnessLength,
    /// Local non-dev zkVM execution or proving failed.
    #[cfg(feature = "local-prove")]
    #[error("zkVM execution or proving failed: {0}")]
    Zkvm(#[from] anyhow::Error),
    /// The local prover returned proof-of-work material outside this profile.
    #[cfg(feature = "local-prove")]
    #[error("local succinct prover unexpectedly returned a work receipt")]
    WorkReceipt,
    /// The receipt is not valid for the exact checked-in method image.
    #[error("zkVM receipt verification failed: {0}")]
    Receipt(#[from] VerificationError),
    /// The journal is not the exact fixed statement length.
    #[error("receipt journal length mismatch: expected {expected}, got {actual}")]
    JournalLength {
        /// Required bytes.
        expected: usize,
        /// Received bytes.
        actual: usize,
    },
    /// The authenticated journal differs from the statement expected by the caller.
    #[error("receipt journal differs from the expected public statement")]
    JournalMismatch,
    /// The journal embeds a program identity other than this method image ID.
    #[error("public statement program ID differs from the receipt method image ID")]
    ProgramId,
    /// The journal selects a profile other than the exact frozen preactivation profile.
    #[error("public statement profile ID differs from the frozen EIP-0045 profile")]
    ProfileId,
    /// The host receipt is not a succinct proof accepted by the target profile.
    #[error("zkVM receipt is not succinct")]
    ReceiptKind,
    /// The succinct receipt uses a hash suite outside the target profile.
    #[error("succinct receipt hash suite is not poseidon2")]
    HashSuite,
    /// This multi-segment guest did not terminate in the exact allowed join program.
    #[error("succinct receipt terminal control is not the frozen join program")]
    TerminalControl,
    /// The raw seal has a length outside the exact profile grammar.
    #[error("raw succinct seal length mismatch: expected {expected}, got {actual}")]
    RawSealLength {
        /// Required bytes.
        expected: usize,
        /// Received bytes.
        actual: usize,
    },
    /// The raw seal carries an outer recursion exponent outside the exact profile.
    #[error("raw succinct seal outer po2 mismatch: expected {expected}, got {actual}")]
    OuterPo2 {
        /// Required exponent.
        expected: u32,
        /// Received exponent.
        actual: u32,
    },
    /// The fixed public journal is not a canonical bridge statement.
    #[error("invalid public bridge statement: {0}")]
    Statement(#[from] StatementError),
}

/// A locally generated EIP-0045 profile candidate plus its non-consensus receipt oracle.
#[cfg(feature = "local-prove")]
pub struct VerifiedProofRun {
    /// Host receipt retained only as a local upstream verification oracle.
    pub receipt: Receipt,
    /// Exact four-chunk proof transport consumed by the EIP-0045 opcode ABI.
    pub proof_chunks: [Vec<u8>; 4],
    /// Guest execution cycle accounting returned by RISC Zero.
    pub stats: SessionStats,
}

struct SuccinctProfileView<'a> {
    hashfn: &'a str,
    control_id: &'a [u8],
    seal_words: &'a [u32],
    raw_seal: &'a [u8],
}

/// Return the exact generated method image identity as canonical digest bytes.
pub fn method_program_id() -> [u8; 32] {
    let digest: Digest = BRIDGE_VALIDITY_GUEST_ID.into();
    digest
        .as_bytes()
        .try_into()
        .expect("RISC Zero digest is 32 bytes")
}

/// Build a real local non-dev succinct proof candidate and verify every profile binding.
#[cfg(feature = "local-prove")]
pub fn prove_and_verify_native_witness(
    encoded_witness: &[u8],
    expected_statement: &[u8; EIP0045_BRIDGE_STATEMENT_V1_BYTES],
) -> Result<VerifiedProofRun, HostError> {
    if encoded_witness.len() > MAX_BRIDGE_VALIDITY_GUEST_WITNESS_V1_BYTES {
        return Err(HostError::WitnessTooLarge {
            actual: encoded_witness.len(),
            max: MAX_BRIDGE_VALIDITY_GUEST_WITNESS_V1_BYTES,
        });
    }
    validate_public_journal_for_profile(expected_statement)?;
    let witness_len = u32::try_from(encoded_witness.len()).map_err(|_| HostError::WitnessLength)?;
    let env = ExecutorEnv::builder()
        .write_slice(&[witness_len])
        .write_slice(encoded_witness)
        .build()?;
    let opts = ProverOpts::succinct()
        .with_dev_mode(false)
        .with_prove_guest_errors(false);
    debug_assert!(!opts.dev_mode());
    debug_assert_eq!(opts.hashfn, "poseidon2");
    debug_assert!(!opts.prove_guest_errors);
    let verifier_context = VerifierContext::default().with_dev_mode(false);
    debug_assert!(!verifier_context.dev_mode());
    let prover = LocalProver::new("bridge-eip0045-risc0-v3-succinct");
    let ProveInfo {
        receipt,
        stats,
        work_receipt,
        ..
    } = prover.prove_with_ctx(env, &verifier_context, BRIDGE_VALIDITY_GUEST_ELF, &opts)?;
    if work_receipt.is_some() {
        return Err(HostError::WorkReceipt);
    }
    receipt.verify_with_context(&verifier_context, BRIDGE_VALIDITY_GUEST_ID)?;
    let proof_chunks = verify_eip0045_profile_receipt(&receipt, expected_statement)?;
    Ok(VerifiedProofRun {
        receipt,
        proof_chunks,
        stats,
    })
}

/// Verify a receipt against the exact method, journal bytes, and embedded program identity.
pub fn verify_bridge_validity_receipt(
    receipt: &Receipt,
    expected_statement: &[u8; EIP0045_BRIDGE_STATEMENT_V1_BYTES],
) -> Result<(), HostError> {
    receipt.verify(BRIDGE_VALIDITY_GUEST_ID)?;
    validate_public_journal(&receipt.journal.bytes, expected_statement)
}

/// Verify the exact preactivation EIP-0045 profile and derive its canonical proof chunks.
pub fn verify_eip0045_profile_receipt(
    receipt: &Receipt,
    expected_statement: &[u8; EIP0045_BRIDGE_STATEMENT_V1_BYTES],
) -> Result<[Vec<u8>; 4], HostError> {
    verify_bridge_validity_receipt(receipt, expected_statement)?;
    validate_public_journal_for_profile(expected_statement)?;
    let InnerReceipt::Succinct(succinct) = &receipt.inner else {
        return validate_eip0045_profile_view(None);
    };
    let raw_seal = succinct.get_seal_bytes();
    validate_eip0045_profile_view(Some(SuccinctProfileView {
        hashfn: &succinct.hashfn,
        control_id: succinct.control_id.as_bytes(),
        seal_words: &succinct.seal,
        raw_seal: &raw_seal,
    }))
}

fn validate_eip0045_profile_view(
    view: Option<SuccinctProfileView<'_>>,
) -> Result<[Vec<u8>; 4], HostError> {
    let Some(view) = view else {
        return Err(HostError::ReceiptKind);
    };
    if view.hashfn != "poseidon2" {
        return Err(HostError::HashSuite);
    }
    if view.control_id != EIP0045_RISC0_V3_JOIN_CONTROL_ID {
        return Err(HostError::TerminalControl);
    }
    if view.seal_words.get(32).copied() != Some(EIP0045_RISC0_V3_OUTER_PO2) {
        return Err(HostError::OuterPo2 {
            expected: EIP0045_RISC0_V3_OUTER_PO2,
            actual: view.seal_words.get(32).copied().unwrap_or(u32::MAX),
        });
    }
    chunk_raw_seal(view.raw_seal)
}

fn validate_public_journal(
    journal: &[u8],
    expected_statement: &[u8; EIP0045_BRIDGE_STATEMENT_V1_BYTES],
) -> Result<(), HostError> {
    if journal.len() != EIP0045_BRIDGE_STATEMENT_V1_BYTES {
        return Err(HostError::JournalLength {
            expected: EIP0045_BRIDGE_STATEMENT_V1_BYTES,
            actual: journal.len(),
        });
    }
    if journal != expected_statement {
        return Err(HostError::JournalMismatch);
    }
    let statement = decode_eip0045_bridge_statement_v1(journal)?;
    if statement.program_id != method_program_id() {
        return Err(HostError::ProgramId);
    }
    Ok(())
}

fn validate_public_journal_for_profile(
    expected_statement: &[u8; EIP0045_BRIDGE_STATEMENT_V1_BYTES],
) -> Result<(), HostError> {
    validate_public_journal(expected_statement, expected_statement)?;
    let statement = decode_eip0045_bridge_statement_v1(expected_statement)?;
    if statement.profile_id != EIP0045_RISC0_V3_SUCCINCT_PROFILE_ID {
        return Err(HostError::ProfileId);
    }
    Ok(())
}

fn chunk_raw_seal(raw_seal: &[u8]) -> Result<[Vec<u8>; 4], HostError> {
    if raw_seal.len() != EIP0045_RISC0_V3_RAW_SEAL_BYTES {
        return Err(HostError::RawSealLength {
            expected: EIP0045_RISC0_V3_RAW_SEAL_BYTES,
            actual: raw_seal.len(),
        });
    }
    let mut offset = 0usize;
    Ok(EIP0045_RISC0_V3_PROOF_CHUNK_BYTES.map(|length| {
        let chunk = raw_seal[offset..offset + length].to_vec();
        offset += length;
        chunk
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use bridge_validity_composition::test_vectors::{
        native_bridge_validity_fixture_for_profile_and_contract_v1,
        native_bridge_validity_fixture_v1,
    };
    use bridge_validity_statement::derive_contract_id;

    #[test]
    fn binds_the_public_statement_to_the_exact_method_id() {
        let expected_method_id: [u8; 32] =
            hex::decode("5b46bf0ef2ff959327bfb39c6ac4dae48d509a0fcf91f89dcf84b26f44203934")
                .unwrap()
                .try_into()
                .unwrap();
        assert_eq!(method_program_id(), expected_method_id);

        let fixture = native_bridge_validity_fixture_v1(method_program_id());
        validate_public_journal(&fixture.statement, &fixture.statement).unwrap();

        let mut wrong_program = fixture.statement;
        wrong_program[91] ^= 1;
        assert!(matches!(
            validate_public_journal(&wrong_program, &wrong_program),
            Err(HostError::ProgramId)
        ));
        assert!(matches!(
            validate_public_journal(&fixture.statement[..812], &fixture.statement),
            Err(HostError::JournalLength { .. })
        ));
    }

    #[test]
    fn freezes_the_profile_identity_and_raw_seal_partition() {
        assert_eq!(
            hex::encode(EIP0045_RISC0_V3_SUCCINCT_PROFILE_ID),
            "23c4a123ffb33a1c8db89436fe0e7972bd8e4e289459ee5fd71be5440607d383"
        );
        assert_eq!(
            hex::encode(EIP0045_RISC0_V3_JOIN_CONTROL_ID),
            "7a8f24092c34ed3eb81b3d0a0b796c588c615d3488ef9e61c21dbd1e4b83ea6e"
        );
        assert_eq!(EIP0045_RISC0_V3_OUTER_PO2, 18);
        assert_eq!(EIP0045_RISC0_V3_RAW_SEAL_BYTES, 222_668);
        assert_eq!(
            EIP0045_RISC0_V3_PROOF_CHUNK_BYTES,
            [65_535, 65_535, 65_535, 26_063]
        );

        let proposition = hex::decode(concat!(
            "1c53020e205b46bf0ef2ff959327bfb39c6ac4dae48d509a0fcf91f89dcf84b26f44203934",
            "0e2023c4a123ffb33a1c8db89436fe0e7972bd8e4e289459ee5fd71be5440607d383",
            "d1b9e4e3001ae4e3010e73007301"
        ))
        .unwrap();
        assert_eq!(
            derive_contract_id(&proposition).unwrap(),
            EIP0045_BRIDGE_VALIDITY_CONSUMER_CONTRACT_ID
        );

        let fixture = native_bridge_validity_fixture_for_profile_and_contract_v1(
            EIP0045_RISC0_V3_SUCCINCT_PROFILE_ID,
            method_program_id(),
            EIP0045_BRIDGE_VALIDITY_CONSUMER_CONTRACT_ID,
        );
        validate_public_journal_for_profile(&fixture.statement).unwrap();
        assert_eq!(
            decode_eip0045_bridge_statement_v1(&fixture.statement)
                .unwrap()
                .contract_id,
            EIP0045_BRIDGE_VALIDITY_CONSUMER_CONTRACT_ID
        );

        let mut wrong_profile = fixture.statement;
        wrong_profile[59] ^= 1;
        assert!(matches!(
            validate_public_journal_for_profile(&wrong_profile),
            Err(HostError::ProfileId)
        ));

        let raw_seal = vec![0x5a; EIP0045_RISC0_V3_RAW_SEAL_BYTES];
        let chunks = chunk_raw_seal(&raw_seal).unwrap();
        assert_eq!(
            chunks.each_ref().map(Vec::len),
            EIP0045_RISC0_V3_PROOF_CHUNK_BYTES
        );
        assert_eq!(chunks.concat(), raw_seal);
        assert!(matches!(
            chunk_raw_seal(&vec![0; EIP0045_RISC0_V3_RAW_SEAL_BYTES - 1]),
            Err(HostError::RawSealLength { .. })
        ));
    }

    #[test]
    fn rejects_each_non_profile_succinct_receipt_field() {
        let terminal_control =
            hex::decode("7a8f24092c34ed3eb81b3d0a0b796c588c615d3488ef9e61c21dbd1e4b83ea6e")
                .unwrap();
        let mut seal_words = vec![0u32; 33];
        seal_words[32] = 18;
        let raw_seal = vec![0u8; 222_668];

        let valid = SuccinctProfileView {
            hashfn: "poseidon2",
            control_id: &terminal_control,
            seal_words: &seal_words,
            raw_seal: &raw_seal,
        };
        assert_eq!(
            validate_eip0045_profile_view(Some(valid))
                .unwrap()
                .each_ref()
                .map(Vec::len),
            [65_535, 65_535, 65_535, 26_063]
        );

        assert!(matches!(
            validate_eip0045_profile_view(None),
            Err(HostError::ReceiptKind)
        ));
        assert!(matches!(
            validate_eip0045_profile_view(Some(SuccinctProfileView {
                hashfn: "sha-256",
                control_id: &terminal_control,
                seal_words: &seal_words,
                raw_seal: &raw_seal,
            })),
            Err(HostError::HashSuite)
        ));

        let mut wrong_terminal = terminal_control.clone();
        wrong_terminal[0] ^= 1;
        assert!(matches!(
            validate_eip0045_profile_view(Some(SuccinctProfileView {
                hashfn: "poseidon2",
                control_id: &wrong_terminal,
                seal_words: &seal_words,
                raw_seal: &raw_seal,
            })),
            Err(HostError::TerminalControl)
        ));

        let mut wrong_outer = seal_words.clone();
        wrong_outer[32] = 17;
        assert!(matches!(
            validate_eip0045_profile_view(Some(SuccinctProfileView {
                hashfn: "poseidon2",
                control_id: &terminal_control,
                seal_words: &wrong_outer,
                raw_seal: &raw_seal,
            })),
            Err(HostError::OuterPo2 {
                expected: 18,
                actual: 17
            })
        ));
    }
}
